application: dancebook-2016
version: 1
runtime: php55
api_version: 1

handlers:
- url: /src
  static_dir: dist/src/

- url: /.*
  script: /dist/index.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules$
- ^src$
- ^.gitignore$
- ^README.md$
- ^gulpfile.js$
- ^package.json$
