application: dancebook-2016
version: 1
runtime: php55
api_version: 1

handlers:
- url: /src
  static_dir: dist/src/

# - url: /mobile/src
#   static_dir: dist/mobile/src/

- url: /create-form
  script: /dist/create_form.html

- url: /teams
  script: /dist/team_page.html

- url: /events
  script: /dist/event_page.html

- url: /
  script: /dist/index.html

skip_files:
- ^(.*/)?#.*#$
- ^(.*/)?.*~$
- ^(.*/)?.*\.py[co]$
- ^(.*/)?.*/RCS/.*$
- ^(.*/)?\..*$
- ^node_modules$
- ^src$
- ^.gitignore$
- ^README.md$
- ^gulpfile.js$
- ^package.json$
